### ISSUE TITLE
Error running kickstart script at line 29 ... EFI mode not detected

### ISSUE THREAD

**Issue by JohnAtl** [ublue-os/main#169]
### What happened?

Installing universalblue-38-x86_64-20230418.iso from a USB stick.
```
There was an error running the kickstart script at line 29. This is a fatal
error and installation will be aborted. The details of this error are:

EFI mode not detected. Skipping key enrollment.
0
EFI variables are not supported on this system
```
After clicking Exit Installer, the system reboots and appears normal.

**Comment by akdev1l** [comment]
Oh hi we already fixed this issue in the latest ISO 

There is actually no impact to this and the system should work just fine! 

The issue was basically just that we accidentally forgot to tell the system non-EFI systems are OK :-)

you should be good and the issue should not happen with the latest iso 

thanks for reporting this!

**Comment by castrojo** [comment]
I saw this recently too:

I originally was just going to blow the VM away but then I rebooted it and everything was fine, so you shouldn't need to reinstall!

**Comment by JohnAtl** [comment]
Thanks!
