### ISSUE TITLE
both drives checked during the installation process by default

### ISSUE THREAD

**Issue by antonispgs** [ublue-os/main#174]
### What happened?

Main ISO had both drives checked during the installation process by default

### Relevant log output

```shell
Not sure if it is even a bug but while trying to install, both drives were selected. My NVME and my SSD backup drive. I failed to see it so the system got installed on both drives automatically. I confirmed it when i run the ISO for a second time. When multiple drives exist, it seems to have both selected by default. In any case, it is still my fault for omitting to observe this, however it might be better if none of the drives was preselected, like fedora does.
```

**Comment by akdev1l** [comment]
Hi thanks for filing this, I'll doble check because all those actions should be manually already

Just tracking so I can double check

**Comment by jroyvde** [comment]
Had the same with universalblue-38-x86_64-20230421. All five of my drives were selected by default.

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better.

I'm not sure if the double checks are still a problem, if someone could confirm that that would be awesome.
