### ISSUE TITLE
Boots into blank screen on tty1

### ISSUE THREAD

**Issue by Doosty** [ublue-os/main#187]
This image boots into black screen, switching to any other tty works. Bsherman on discord gave me a solution to enable this systemd service either at runtime or inside Containerfile `RUN systemctl enable getty@tty1`.

**Comment by castrojo** [comment]
Note: this is for base-main, which doesn't come with a desktop. We should document this.

**Comment by manan-gup** [comment]
I ran into this yesterday and randomly tried switching to a different tty and it worked (like its mentioned above). But I was almost about to reinstall with another version. Its not obvious whether the system is bricked or not. 

If its as simple as adding this to the Containerfile then we can change it instead of documenting a workaround, right?
> `RUN systemctl enable getty@tty1`

**Comment by castrojo** [comment]
Yeah I think if someone PRs in for this just for -base that would do the trick?

**Comment by manan-gup** [comment]
I'll do it. Thanks for the quick response. Is reading the stuff [here](https://universal-blue.discourse.group/c/contributing/7) enough to set me up to begin contributing?

**Comment by castrojo** [comment]
https://universal-blue.org/CONTRIBUTING/ is the Canonical text, though I should have pointers to that from the forum, I'll make sure I get on that, thanks!
