### ISSUE TITLE
Add xdg-terminal-exec

### ISSUE THREAD

**Issue by orowith2os** [ublue-os/main#211]
### Describe the package

GNOME/GLib currently uses xdg-terminal-exec as the first terminal binary, and then falls back to other terminals, like Console and Terminal. 

Having xdg-terminal-exec would not only allow an easy way to set the default terminal, it would help get the script to be tested in the real world and maybe find more bugs that can be fixed with it.

The dconf preference on GNOME for the default terminal is deprecated and will not be used on recent versions of GNOME. 

### Information on the package

https://github.com/Vladimir-csp/xdg-terminal-exec

There is no Fedora package available as of now, but this is a simple script, so it could be put into the user's bin directories (like /usr/local/bin) fairly easily.

This may break existing setups that rely on the hardcoded terminal binaries. In response to that, I say: we should try and make the current hardcoded GLib terminals Just Work with xdg-terminal-exec. For the time being, we can go down the list of terminals in GLib's list and provide a desktop file with each of them that works with xdg-terminal-exec. 

### Image

Silverblue

**Comment by bigpod98** [comment]
from my limited testing in silverblue unless you have gnome terminal or xterm(not shipped with fedora silverblue or ublue silverblue ootb) or another terminal preprepared to work with xdg-terminal-exec, opening an app from desktop that is run in terminal doesnt open anything, including no error message.

**Comment by orowith2os** [comment]
> opening an app from desktop that is run in terminal doesnt open anything, including no error message.

That's one thing I meant by finding bugs that can be fixed. And this shouldn't be too much of a worry if you relied on GLib's autodetection, as ideally several premade desktop files will be shipped, and ideally upstreamed.

**Comment by bigpod98** [comment]
based on this limited testing i would propose holding on any changes as it is fairly disruptive. 
as of writing i couldnt find anything regarding fedora adopting this proposed spec.

**Comment by Arcitec** [comment]
> as ideally several premade desktop files will be shipped, and ideally upstreamed.

Unfortunately, this won't work. This is an immutable distro. Most people would do something like this:

```sh
rpm-ostree remove gnome-terminal gnome-terminal-nautilus
flatpak install --system com.raggesilver.BlackBox
```

If we ship pre-made .desktop files that contain the necessary `X-ExecArg=-x` (or whatever argument each specific terminal needs for launching a custom command), then we have to guess:

- Is the user layering the package? Then our pre-made desktop file must link to the local install (at correct path, mind you).
- Is the user a Flatpak user? Then our pre-made desktop file must link to the flatpak install instead.

**Comment by orowith2os** [comment]
@Arcitec that's why upstreaming the patches is a good idea. For terminals already shipped in Flatpak, the fix would get to end users fairly quickly. For normal packages, they'd have to be shipped as a patch for the time being.

**Comment by Arcitec** [comment]
## What is xdg-terminal-exec?

- It isn't an accepted spec. It was a random person's proposal to the XDG, and it was rejected.
- It isn't packaged by Fedora.
- It's just a small shell script, with a vastly over-complicated design.
- It was only temporarily added to GLib, to appease people who were annoyed that GNOME had removed the dconf flags for switching terminal. They put it at the [top of the terminal binary list](https://gitlab.gnome.org/GNOME/glib/-/blob/2.76.2/gio/gdesktopappinfo.c?ref_type=tags#L2701-2713), which means that if it's detected on the system, it gets launched as if it's the terminal binary.
- Their plan is to remove it from GLib after they finish work on another spec called `xdg-default-apps` instead, since `xdg-terminal-exec` is an overcomplicate and hacky script.
- By default, it does nothing unless it has been configured by the user or distro, and if it can't find a configuration then it falls back to trying to launch `xterm`, which in turn doesn't exist on Silverblue, so we end up with absolutely nothing: We break user's desktops. They see nothing on screen when they try to launch `Terminal=true` based app shortcuts.
- If we *don't* ship that binary (as we currently don't), then GLib instead "properly" uses the list (linked above) of known terminal binaries to auto-detect which one the user has installed.

## Installation

I already use it on my own custom image, since its purpose doesn't surprise me and I've done the necessary setup in my own image. Here's how to install it system-wide:

```sh
wget "https://raw.githubusercontent.com/Vladimir-csp/xdg-terminal-exec/master/xdg-terminal-exec" -O "/usr/bin/xdg-terminal-exec"
chmod +x "/usr/bin/xdg-terminal-exec"
```

However, it can (and I think this is the best way) be installed manually for any users who want it, by simply doing the following;

```sh
mkdir -p ~/.local/bin
wget "https://raw.githubusercontent.com/Vladimir-csp/xdg-terminal-exec/master/xdg-terminal-exec" -O ~/.local/bin/xdg-terminal-exec
chmod +x ~/.local/bin/xdg-terminal-exec
```

## Configuration of Terminals

Every terminal that you want to support needs to have a magical `X-ExecArg=-x` value added to its `.desktop` file (where `-x` should be set to whatever argument the terminal binary needs to be given to accept a "custom command to execute"). Most terminals don't have that in their `.desktop` files. GNOME Terminal has it, but that's most likely because they saw that GLib added temporary support for it and wanted to be sure GNOME Terminal would still work.

Furthermore, every terminal's `.desktop` file must be a file or symlink inside a special "xdg-terminal-exec data directory". It doesn't just use the normal system's desktop files (that's probably a big part of why it was rejected due to being so overly complicated).

Here's an example of setting up a terminal on the **per-user** level, to illustrate the messy process:

1. Create the xdg-terminal-exec data folder.

```sh
mkdir -p ~/.local/share/xdg-terminals/
```

2. Copy the desired terminal desktop file to your local app folder. If you use the Flatpak app, then you must have the Flatpak version of the `.desktop` file. If you use a native app, then you must havae the native version of the `.desktop` file. That is why we cannot ship pre-configured desktop files.

```sh
cp /usr/share/applications/com.gexperts.Tilix.desktop ~/.local/share/applications/
```

3. Edit your local desktop file in a text editor, such as the `~/.local/share/applications/com.gexperts.Tilix.desktop` file in this example.

4. Insert the magical, required string next to its normal `Exec=` line. Use the flags that your terminal requires for launching arbitrary commands. Example:

```
X-ExecArg=-e
```

5. Symlink the modified desktop file into xdg-terminal-exec's data folder.

```sh
ln -s ~/.local/share/applications/com.gexperts.Tilix.desktop ~/.local/share/xdg-terminals/com.gexperts.Tilix.desktop
```

Now that terminal is ready to be launched by `xdg-terminal-exec`. But you aren't done yet.

Next, we need...

## User Configuration

It's not enough to configure the terminal itself above. You must also manually tell `xdg-terminal-exec` which terminal you want to run. That's done as follows...

1. Open `~/.config/xdg-terminals.list` in a text editor.

2. Write the name of the ".desktop" file of the intended terminal into that config file. Example:

`com.gexperts.Tilix.desktop`

If that file doesn't exist or nothing is written into it, then `xdg-terminal-exec` falls back to trying to launch `xterm`, which doesn't exist on Silverblue, so all attempts to launch terminal apps breaks.

## If any of these steps are skipped...

Then the system breaks.

That's bad. Installing `xdg-terminal-exec` breaks GLib's automatic detection of what terminal you've got installed. It will instead only run xdg-terminal-exec. Nothing else. And if it isn't configured, then it's Game Over for our users. They won't see any terminal apps when launching terminal-based app shortcuts. Their systems simply stop working.

## Upstreaming `X-ExecArg` into upstream desktop files?

It helps a little bit with one small part of the process (adding the ExecArg), but...

1. The spec is rejected, so `X-ExecArg` is a "dead argument" that we'll be asking people to insert. I am sure many will refuse.
2. Adding the argument is just one small part. We also need to create symlinks from `xdg-terminal-exec`'s data directory to the actual `.desktop` file. Which doesn't happen automatically when you install Flatpak versions of terminals. In fact, only GNOME Terminal (native package) ships the necessary symlink by default. Every other terminal would be broken.
3. We would have to create symlinks to every location of `.desktop` files, pre-emptively.
4. We can't do that, since we don't know the location of the user's `.desktop` files. So even if we get `X-ExecArg=` into every upstream Terminal's `.desktop` file, we are still completely screwed and unable to ship this to users "seamlessly", because we simply cannot know where those `.desktop` file will exist on disk.
5. We can only create 1 link per app. We'd have to guess: Is it native? System flatpak? Or user flatpak? We can only link to one of those potential `.desktop` locations from `xdg-terminal-exec`'s data dir. Now it becomes even clearer why the spec was rejected.

## Better alternatives...

You know all that complicated setup above? There's a simpler solution. And I don't mean simpler for us. I don't mean simpler for distro packagers. I don't mean simpler for terminal app maintainers... I literally mean simpler for *the users*. It's _literally_ easier than configuring the overly complicated `xdg-terminal-exec`'s configuration files, desktop file edits, creating data directories and creating symlinks. And it illustrates well why the spec was deemed badly designed and rejected:

1. We know that GLib looks for `xdg-terminal-exec` as a binary, and simply submits the "command to run" as the first argument to it.

2. So, instead of going through alllllll that arcane ritual stuff above, you can just create the file and stick the exact terminal into it. So create `~/.local/bin/xdg-terminal-exec` in a text editor, save it with the following example contents, and you're done. Way easier than trying to follow the rejected spec.

Launching native Tilix:

```sh
#!/usr/bin/env bash

tilix -e "$@"
```

If you instead want to launch Flatpak Blackbox (not tested, but the principle is like this):

```sh
#!/usr/bin/env bash

flatpak run com.raggesilver.BlackBox -- "$@"
```

Suddenly it becomes clear why it isn't even worth attempting to follow the arcane rituals. It's literally easier to create your own script to launch the exact terminal you want. With just 1 config file and just 1 line of actual code/config.

**Comment by orowith2os** [comment]
I'll look into reimplementing xdg-terminal-exec but without some of it's design flaws in a bit to hopefully address most everything.

**Comment by Arcitec** [comment]
> I'll look into reimplementing xdg-terminal-exec but without some of its design flaws in a bit to hopefully address most everything.

That would be a great idea.

The worst issue is the `X-ExecArg=...` in the `.desktop` files, since it's a nightmare to add that to desktop files. But the need to manually symlink specific desktop files is horrific too.

Something where you can just say the desktop file's  basic name *and* the argument would be ideal. Imagine if we could just do this in a `~/.config/xdg-terminal-exec.list` (slightly changed config filename to avoid confusion?):

```
com.raggesilver.BlackBox.desktop -c
```

And then have it automatically scan for the matching `.desktop` file (using XDG priority) and then launch it with the given `-c <command line>` arg. That would be a good solution.

Just remember that it would need to have a fallback that also scans for all of GLib's normal defaults seamlessly, if no config is found:

https://gitlab.gnome.org/GNOME/glib/-/blob/2.76.2/gio/gdesktopappinfo.c?ref_type=tags#L2701-2713

**Comment by Arcitec** [comment]
@orowith2os Oh wait... keep one thing in mind: If this is a proposal for shipping the binary inside uBlue, then it'd be installed at `/usr/bin/xdg-terminal-exec` (or `/usr/local/bin`) which means it's immutable, so editing the config via editing the script itself won't work.

But if it's a different proposal, to just have something anyone can drop into their local `~/.local/bin/xdg-terminal-exec` then the solution sounds nice.

Just asking, since this discussion is about adding something to the uBlue images' system-wide install by default.

**Comment by orowith2os** [comment]
> which means it's immutable, so editing the config via editing the script itself won't work.

This would be written in Rust, so you'd be editing binary even if it was mutable ;)

I'll write everything to a unified config file with all the terminals and everything so it's not hardcoded but can still fall back to some defaults.

**Comment by bigpod98** [comment]
currently i still think we should wait a bit to see this play out more, specifically how our upstream fedora handles this entire thing, there is no need to my knowledge that we need to act now.

**Comment by bigpod98** [comment]
What is the case with other desktop environments oustide of gnome do they use this same proposed spec

**Comment by Arcitec** [comment]
> What is the case with other desktop environments oustide of gnome do they use this same proposed spec

Nobody else uses it and FreeDesktop has no interest in accepting it.

The only reason this is even a discussion or proposal is because GNOME decided to remove the old `dconf` variables that *used to be* able to set a "terminal binary and launch argument". Typical GNOME fashion (I use GNOME too...), where they remove something without a replacement solution. Users were understandably upset that they could no longer choose which terminal GNOME uses when launching desktop shortcuts.

GNOME just begrudgingly added `xdg-terminal-exec` because they were tired of being told to manually add new terminals to the list of supported terminals in `GLib`. And they said okay since it was a simple matter of [adding 1 line](https://gitlab.gnome.org/GNOME/glib/-/blob/2.76.2/gio/gdesktopappinfo.c?ref_type=tags#L2701-2713) to place `xdg-terminal-exec` as the first "Terminal binary" in the list, so [they decided to temporarily add it](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2839/diffs?commit_id=22e1b9bcc0ca7cd1ba2457ddf5b5545752f9c7ea), and announced that that they won't be updating the terminal list manually anymore.

They decided that it will be removed from GNOME again when [xdg-default-apps](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/54) has a mechanism for handling "default terminal". But that proposal seems to be stalled due to lack of consensus, if you check the comments.

**Comment by castrojo** [comment]
> Yes, there's no need, but it would vastly improve the user experience to have some sort of xdg-terminal-exec for the GNOME images.

I'm down to play, I've added this to bluefin and will follow up on how to set up blackbox and stuff: 

https://github.com/ublue-os/bluefin/pull/223

**Comment by orowith2os** [comment]
I've published my source code to my GitLab, it's almost ready. Just need to sort out a few more things until it's ready. Contributions greatly appreciated!

https://gitlab.com/OroWith2Os/xdg-terminal-exec

**Comment by mcepl** [comment]
> * It's just a [messy shell script](https://raw.githubusercontent.com/Vladimir-csp/xdg-terminal-exec/master/xdg-terminal-exec), with a vastly over-complicated design.

Overcomplicated? 359 lines of shell script doesn’t sound so bad.

**Comment by mcepl** [comment]
> The worst issue is the `X-ExecArg=...` in the `.desktop` files, since it's a nightmare to add that to desktop files.

Why? Changing of like 20 `.desktop` files (how many terminals is out there relevant for Fedora?) doesn’t seem like to much a big deal.

**Comment by castrojo** [comment]
Downstreams are using Ptyxis now.
