### ISSUE TITLE
docs: contributing.md needs instructions for local hosting

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#23]
I've checked in an initial contributing.md but it needs instructions for firing up a registry on your machine or local network and pushing to it. A simple one like docker/registry is probably more appropriate than k8s/harbor. 😄

**Comment by tepene** [comment]
At the moment I'm using the following workflow:

## On my host system where I'm developing

1. I'm using host names instead of localhost. So I added the following to `/etc/hosts`
  ```ini
  # Container registry
  127.0.0.1 registry.dev.local
  ```

2. Run registry on localhost
  `podman run -d --name registry.dev.local -p 5000:5000 docker.io/library/registry:latest`

2. Build image
  `podman build . -t registry.dev.local:5000/ublue-bayou:dev-latest --build-arg RECIPE=recipe.yml`

3. Upload image to registry on localhost
  `podman push --tls-verify=false registry.dev.local:5000/ublue-bayou:dev-latest` 

## On my Boxes Test VM where I'm testing

1. The boxes VM needs to find the registry on my host system. So I added the following to `/etc/hosts`
  ```ini
  # Container registry
  10.0.2.2 registry.dev.local
  ```

  The ip is the default gateway of my Boxes setup, to evaluate your default gateway ip, you can run `ip route | grep "default via" | cut -d ' ' -f 3`

2. Since the registry is running insecure I added the file `/etc/containers/registries.conf.d/ublue-bayou-dev.conf` with
  ```toml
  [[registry]]
  location = "registry.dev.local:5000"
  insecure = true
  ```

3. I rebase my image
  `rpm-ostree rebase ostree-unverified-registry:registry.dev.local:5000/ublue-bayou:dev-latest`

At the moment I set the configuration manually on the Test system but I'm wondering if this could be included in the building process. Like, when `--build-arg DEV=true` include the Boxes Test config otherwise not.

**Comment by castrojo** [comment]
This is awesome, would you mind PRing this into this page? https://github.com/ublue-os/website/blob/main/docs/CONTRIBUTING.md

If not I can do it for you, let me know!

**Comment by tepene** [comment]
yeah, sure. I will PR it.

**Comment by castrojo** [comment]
This is mostly done and in the docs, thanks everyone!
