### ISSUE TITLE
Unique name on a bootloader

### ISSUE THREAD

**Issue by xalt7x** [ublue-os/main#24]
For now it's hard to distinguish regular and modded Silverblue on a bootloader
(user needs  to remember ostree entry number)

![2023-02-21_11-39](https://user-images.githubusercontent.com/44649402/220307581-7d027564-2b8b-4e50-bde0-0ff264fb0372.png)

**Comment by aorith** [comment]
For the `rpm-ostree status` we have to set the label `org.opencontainers.image.version`:

```
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-registry:ghcr.io/aorith/blueconfig:stable
                   Digest: sha256:cef0856b5a62fc25dabd1a9431cd9527c45f99a5f6254ee074de6450d654c3a1
                  Version: 37.20230318.17 (2023-03-18T17:58:01Z)
          LayeredPackages: langpacks-en
```

For the grub entries, I think it's generated with `/etc/grub.d/15_ostree`, that script seems to parse the bootloader entries (`/boot/loader/entries/`) and those entries seem to be generated by ostree.

Everything points towards the `PRETTY_NAME` present in `/usr/lib/os-release`, but I must be missing something because changing that variable doesn't modify the bootloader entries an hence grub entries :(

https://github.com/ostreedev/ostree/blob/d49632faa6cbcda7b2891d5aab9f5a9a68348160/src/libostree/ostree-sysroot-deploy.c#L2022-L2023

**Comment by aorith** [comment]
Seems to be working now:

```
[root@trantor ~]# grep Blueconfig /boot/loader/grub.cfg 
menuentry 'Fedora Linux 37.20230319.08 (Blueconfig) (ostree:0)' --class gnu-linux --class gnu --class os --unrestricted 'ostree-0-1aea2add-32c3-490f-a467-e00166635fa6' {
menuentry 'Fedora Linux 37.20230318.17 (Blueconfig) (ostree:1)' --class gnu-linux --class gnu --class os --unrestricted 'ostree-1-1aea2add-32c3-490f-a467-e00166635fa6' {
```

```
[root@trantor ~]# grep Blueconfig /boot/loader/entries/*
/boot/loader/entries/ostree-1-fedora.conf:title Fedora Linux 37.20230318.17 (Blueconfig) (ostree:1)
/boot/loader/entries/ostree-2-fedora.conf:title Fedora Linux 37.20230319.08 (Blueconfig) (ostree:0)
```

I moved the change to the `PRETTY_NAME` before the `rpm-ostree ex rebuild` command (https://coreos.github.io/rpm-ostree/ex-rebuild/), that might have solved it or maybe a new minor version of the Linux kernel was in the base of the Silverblue image, triggering the rebuild of the menu...

It does work after a clean rebase too but I'm not sure if it will work between `rpm-ostree upgrade`'s  when the update doesn't include a new kernel or something that triggers the rebuild of the grub menu.
