### ISSUE TITLE
Add avif-pixbuf-loader for all images as well, and qt-heif-image-plugin for Kinoite

### ISSUE THREAD

**Issue by bayazidbh** [ublue-os/main#258]
### Describe the package

Following up on #252 #254 #255 : 

- `avif-pixbuf-loader` this is what I recall is needed for AVIF support.
- `qt-heif-image-plugin` this is I recall part of the dependency needed for HEIF support on KDE apps.

### Information on the package

```
Name         : avif-pixbuf-loader
Version      : 0.11.1
Release      : 7.fc38
Architecture : i686
Size         : 17 k
Source       : libavif-0.11.1-7.fc38.src.rpm
Repository   : fedora
Summary      : AVIF image loader for GTK+ applications
URL          : https://github.com/AOMediaCodec/libavif
License      : BSD-2-Clause
Description  : Avif-pixbuf-loader contains a plugin to load AVIF images in GTK+ applications.

Name         : avif-pixbuf-loader
Version      : 0.11.1
Release      : 7.fc38
Architecture : x86_64
Size         : 16 k
Source       : libavif-0.11.1-7.fc38.src.rpm
Repository   : fedora
Summary      : AVIF image loader for GTK+ applications
URL          : https://github.com/AOMediaCodec/libavif
License      : BSD-2-Clause
Description  : Avif-pixbuf-loader contains a plugin to load AVIF images in GTK+ applications.
```

```
Name         : qt-heif-image-plugin
Version      : 0.3.3
Release      : 7.fc37
Architecture : x86_64
Size         : 28 k
Source       : qt-heif-image-plugin-0.3.3-7.fc37.src.rpm
Repository   : rpmfusion-free
Summary      : Qt plugin for HEIF images
URL          : https://github.com/jakar/qt-heif-image-plugin
License      : LGPLv3
Description  : Qt plugin for HEIF images.
```

### Image

All Images

**Comment by fiftydinar** [comment]
AVIF-pixbuf-loader is not needed at all for AVIF format support (tested).
All editions, including Gnome, KDE, Lxqt, Cinnamon, MATE & XFCE support those out of the box.

So I don't agree with including avif-pixbuf-loader into main ISO.

Qt-heif-image-plugin doesn't make KDE display HEIF file formats still, because of kimageformats in Fedora is not built with KIMAGEFORMATS_HEIF build option.

It needs to be tested with libheif-freeworld, libheif-tools, heif-pixbuf-loader & Qt-heif-image-plugin removed.

If KIMAGEFORMATS_HEIF build option works in supporting HEIF, than remove libheif-freeworld, libheif-tools, heif-pixbuf-loader & Qt-heif-image-plugin from Kinoite edition.

If otherwise, add those packages gradually, until satisfying result is achieved.
