### ISSUE TITLE
Unable to deploy ublue: "The command 'ostree container image deploy ...' exited with the code 1."

### ISSUE THREAD

**Issue by pmnlla** [ublue-os/main#295]
### What happened?

Upon attempting to install ublue, the installer states a fatal error has occurred amidst deploying the ublue image.
The installer states that "The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=ghcr.io/ublue-os/silverblue-nvidia:38 --no-signature-verification' exited with code 1.' I have found no way to remedy this so far, but this error also happens with the standard fedora silverblue installer.

### Relevant log output

```shell
To be done - give me a few minutes since the posting of the issue
```

**Comment by bsherman** [comment]
This is likely related to a network hiccup during the downloading of the image during the install process.

https://universal-blue.org/installation/#other-gotchas  gives a few suggests on how to possibly improve the outcome, perhaps using ethernet cable instead of wifi, etc... but we know some users have never been able to get the ISO installer to work.

If you find yourself in that situation, It is suggested to install Fedora Silverblue and then rebase to Universal Blue Silverblue.

**Comment by pmnlla** [comment]
I gave it a new EFI partition and the installer worked fine.
I am my 13th reason.
