### ISSUE TITLE
Aurora Development and Integration

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#533]
This issue tracks the integration of Aurora into Bluefin. 

https://github.com/NiHaiden/aurora

Discussion: https://universal-blue.discourse.group/t/aurora-announcement/767

TODO:

- [x] Build Aurora out of the Bluefin repo
  - [x] Untechdebt the bluefin repo
- [x] Fix F40 builds of devpod for aurora-dx
- [x] Add image info to universal-blue.org - @KyleGospo
- [x] Finish up aurora website - niklas
- [x] Finish ISO hookup to aurora/bluefin - @noelmiller 
- [x] Cloudflare domain + secrets for ISO pushing - niklas an @noelmiller 
- [x] Discord channel
- [x] Forum section with branding - @castrojo 
- [x] Announcement post on the forum

**Comment by castrojo** [comment]
This is blocked by cleaning up the containerfile, but will make this easier.

**Comment by castrojo** [comment]
We'd like to just have Aurora building out of the bluefin repo instead of it's own: https://github.com/ublue-os/bluefin

**Comment by castrojo** [comment]
https://github.com/ublue-os/bluefin/pull/1091

**Comment by m2Giles** [comment]
Aurora 39 is now building inside of bluefin.

Aurora 40 is currently not building due to some issues with akmods and some kernel skew.

Users that were on niklaus' build, will need to do a manual rebase.

We still have some loose threads that need to be accounted for. Users that encounter any are encouraged to report issues in the bluefin repo. We also need to get branding and announcements in place.

**Comment by castrojo** [comment]
Alright, we've got things building: https://github.com/orgs/ublue-os/packages?tab=packages&q=aurora

I added a task list to the top message with what's left to do to finish it off. We have about a week to finish this off if we're going to make F40 release day, no pressure. 🌸

**Comment by m2Giles** [comment]
F40 has been building since we disabled devpod for F40 builds.

**Comment by castrojo** [comment]
Alright, good enough!
