### ISSUE TITLE
Flatpak installer

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/main#69]
Create an application that is responsible for installing Flatpaks on first boot after a user finishes installation. It is intended as a replacement for custom zenity dialogs.

# Project goals
* Config file driven via JSON/YAML
* Support for arbitrary pre and post-install commands
* Configuration driven screens
* Screen independent state management with ability to set defaults
* Extensible with drop-in Python classes / plugins to extend functionality

**Comment by marcoceppi** [comment]
Project is progressing in https://github.com/ublue-os/yafti

**Comment by castrojo** [comment]
Ok Marco's almost done with the RPM packaging, we'll add it to main but without a config file so that users get a stock experience. Then all downstreams need to do is include the yaml file and that'll let them customize what to install on firstboot.

**Comment by EinoHR** [comment]
Great, was just about to comment on why yafti isn't in main yet! I think a default configuration welcoming the user to ublue would be great, so that they could get the flatpak selection screen (as present in bluefin). That way we'd have a uBlue flatpak selection where one could choose what to get at boot.
I think it'd still be possible to inject into that yafti.yml using `yq`, like I'm doing in startingpoint rn.
