### ISSUE TITLE
Generate image list for the website

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/main#70]
Dynamically display all available ublue-os images/flavors on the website updated without human interaction. Each image should display it's name, description, instructions on how to rebase, available tags, links to the github repo, readme, and when available link to ISO / signature for each image

**Comment by EinoHR** [comment]
This issue should probably be a discussion or an issue in the website repo.

I have already tried this on https://github.com/ublue-os/images-website [(view website)](https://ublue-images-demo.netlify.app/) using publicly available APIs and concluded that it's not really possible. I opted instead for a metadata yml file providing extra information useful to the visitor, reasoning for this below.

I see you've started work on an [image scanner](https://github.com/ublue-os/image-scanner-md), which probably uses the [packages API](https://docs.github.com/en/rest/packages?apiVersion=2022-11-28#list-packages-for-an-organization).

I didn't opt for using that, because it required a `read:packages` permission on the org (I would have needed to plead for an API key) and wouldn't have been able to read the container image metadata. I couldn't get the GHCR registry to give out the manifest of the image, either.

I also envisioned for the image website to possibly include community-created images in the future, which wouldn't be possible with the automatic approach.

Please update this thread if you have already/do manage to make it work like that! And please tell me if you think the website I built _just isn't right for this project_, It can be moved out of this org and I might rebrand it as something more general.

**Comment by castrojo** [comment]
Yeah it kind of needs to be automatic due to the amount of images we've created. We could surface the manual list if we updated it: https://github.com/ublue-os/awesome-custom-images

**Comment by marcoceppi** [comment]
I'm going to close this for now. However, the current list is just barely enough. It's re-using markdown formatters but we could embed generated HTML to make this list more impactful and more dynamic. I'll open up issues for those in the future
