### ISSUE TITLE
Optimize for smaller layers

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#94]
We take the list of packages and then send it to `rpm-ostree install`.

https://github.com/ublue-os/main/blob/057d9b843844bd46d7f42db83a5bdef182403805/build.sh#L28

This creates one huge layer. If we had each package be it's own RUN so it maps out like this:

    RUN rpm-ostree install package1
    RUN rpm-ostree install package2

Then this would create smaller layers and would be more efficient instead of one huge layer. I'm guessing that on individual updates it would bring in one layer instead of having to download the huge layer any time any of the packages get updated. 

(We need to look up how many layers are supported by podman)

**Comment by mtalexan** [comment]
This would make the layers smaller, but wouldn't allow updating only one layer. Layers are dependent on all prior layers, so if the install list is ordered by update frequency you'd have fewer small subesequent layers to update, but wouldn't be able to update only one layer.

Docker daemon, but not podman, supports a `COPY --link` instruction that allows a copied layer to explicitly state that it's not dependent on prior layers, but that leaves it to you to be sure it really doesn't touch any files that are modified by prior layers.

All that said, defining the RPM installs as one ostree commit per RPM is probably better than an all-in-one. If it's coordinated between DE images you could get layer and commit re-use between DE images too. The commit re-use has little benefit since the underlying data is already de-dupped with indirection for the blobs by ostree (and usually at a block level by btrfs), but the OCI layer reuse would significantly reduce on-disk usage of the registry.

**Comment by IverCoder** [comment]
I hope Ublue gets more friendlier for people with metered internet connections soon, as updates on certain days get to upwards of half a gigabyte

**Comment by castrojo** [comment]
(Leaving the comment in the right place now): Just to set expectations don't expect efficiency gains any time soon, container diffs would be complex so metered connections should still stay away for a while.

**Comment by tulilirockz** [comment]
This was a really big issue the NixOS developers had to tackle, maybe having some inspiration from them may help out on fixing this. (I personally don't know how would that be implemented though...)

**Comment by noelmiller** [comment]
@castrojo would an offline ISO help in this instance? Or are we talking ongoing updates of images since you need to pull down the entire image each time you update?
